---
# create openstack users
- name: create openstack users in bulk
  hosts: localhost
  connection: local
  sudo: false
  gather_facts: false

  tasks:
    - include_vars: "{{ users_file }}"

    - name: Create users
      os_user:
         state: present
         auth:
           auth_url: http://192.168.0.140:35357/v3
           username: admin
           password: "{{ admin_password }}"
           project_name: trainings
           domain_name: default
         name: "{{ item.key }}"
         password: changeme
         update_password: on_create
         email: "{{ item.value.email }}"
         domain: default
         default_project: trainings
      with_dict: "{{ users }}"

    - name: add role user
      os_user_role:
        auth:
         auth_url: http://192.168.0.140:35357/v3
         username: admin
         password: "{{ admin_password }}""
         project_name: trainings
         domain_name: default
        user: "{{ item.key }}"
        role: user
        project: trainings
      with_dict: "{{ users }}"

    - name: Send slack notification
      slack:
         token: "T02592CKJ/B6BG2CP5L/zLlAaNYwYkJ7qjdBX4VDoxxr"
         msg: "OpenStack user @{{ item.key }} created. Try login to Dashboard http://192.168.0.140/horizon"
         username: '#cloud-support-sg'
      with_dict: "{{ users }}"



    - name: Send email notification
      mail:
          # Sending an e-mail using Gmail SMTP servers
          host: smtp.gmail.com
          port: 465
          username: pbuditi@palo-it.com
          password: {{ mail_password }}
          to: "{{ item.value.email }}"
          subject: OpenStack Notificaton Dev Account created - {{ item.key }}
          body: 'Hi {{ item.value.name }},
                  Welcome to OpenStack Cloud platform of Palo-IT. Kindly note your credentials below.
                     OpenStack Dashboard: http://192.168.0.140/horizon
                     Domain Name: Default
                     Userid: {{ item.key }}
                     Password: changeme
                 This is a system generated message. Ignore this if you already have an account. Also report if you are unable to login
                 Regards
                 OpenStack Admin'
      with_dict: "{{ users }}"